name: image_search_app
description: A starting point for Flutter applications.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.4
  freezed_annotation: ^3.0.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.2  # (iOS 디자인 사용 시 필요)

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true